### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by caprenter** [caprenter/lamrt#7]
@plebster - Unable to send email on the new deployment. 

My fault - we have a contact form test that is set to pass if it fails (I know!) because that is what you'd expect on dev. But forgot to pick that up on live - it should have failed against the old live site -but maybe it wasn't..

Anyway, needs some trouble shooting.

**Comment by caprenter** [comment]
I can see that there have been quite a few spam attempts on the contact page so we might also want to add e.g.
https://www.drupal.org/project/honeypot

**Comment by Plebster** [comment]
there doesn't seem to be an smtp forwarder installed...

https://www.drupal.org/project/smtp

I have had to do this with Wordpress before

**Comment by Plebster** [comment]
I have got this to work on the test env.

I followed this https://techubber.blogspot.com/2017/11/how-to-resolve-drupal-unable-to-send-emails-smtp-authentication-module.html

I changed the recipient to me and used my smtp creds

We need to to install and get the creds for lamrt.org.uk... 

dev -> pre -> live

**Comment by caprenter** [comment]
Good work. It got me wondering how it was done before,since we never installed that module before.

So,I think our solutions in the past have been to enable sendmail on the server.

I googled this about a 'docker-ish' way to this: https://r.je/sendmail-php-docker

@Plebster I think it's worth you having a look at this alternative solution. I guess it's pros and cons about server set up verses Drupal set up.

I do think whatever we do, we should look at an antispam solution as well btw.

**Comment by Plebster** [comment]
I think this worked on a 'bodged' box and has become a victim due to a 'clean' install

the alternative solution involves changing the stock drupal image, something we shouldn't really do on live

best practise would be to find a drupal solution (not sure if mine is that solution) also the implementation of a recaptcha would eliminate most of the spam.

**Comment by Plebster** [comment]
no idea how to place elements...
<img width="1214" alt="Screenshot 2022-02-23 at 15 15 59" src="https://user-images.githubusercontent.com/26409656/155349017-d4d2f5f2-f584-4c77-b35a-d195d2dd8566.png">

**Comment by caprenter** [comment]
I use the honeypot module on BEES - I think it's better/easier

**Comment by Plebster** [comment]
cool, get some smtp creds and we'll get it installed and pushed to live... I've been staring at form screen for too long :S

**Comment by caprenter** [comment]
This is working. Closing the issue
